name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
        
      # Rest of your steps
      - name: Snake Animation
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: karenyov
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save step output
        run: echo "OUTPUT_VALUE=$OUTPUT_VALUE" >> $GITHUB_ENV
